version: '3'
services:
  web:
    restart: always
    build: ./web/.
    ports: 
      - "8080:80"
  words:
    restart: always
    build: ./words/.
    ports: 
        - "8080"
    networks:
      - postgre
  db:
    restart: always
    build: ./db/.
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - postgre
    ports:
      - "5432"
networks:
  postgre: