version: '3'
services:
  web:
    restart: always
    build: ./web/.
    ports: 
      - "8080:80"
    networks:
      - postgre
  words:
    restart: always
    build: ./words/.
    ports: 
        - "8080"
    networks:
      - postgre
  db:
    restart: always
    build: ./db/.
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DATABASE_HOST=127.0.0.1
    networks:
      - postgre
    ports:
      - "5432"
networks:
  postgre: